Icon improvements
TriliumNext/Notes pull request #392
Opened 2024-09-05 07:12 UTC by SiriusXT

Mainly add missing icon tips
![图片](https://github.com/user-attachments/assets/f67c8abf-90c8-46e7-986c-4bd2f1a46eec)

2024-09-05 08:57 UTC, JYC333 approved these changes

2024-09-08 20:01 UTC, eliandoran requested changes
Please also solve the merge conflict.

2024-09-08 20:01 UTC, eliandoran commented on docs/frontend_api/entities_fnote.js.html
> +    "relationMap": "bx bxl-graphql",
Hmm... are we sure we want to associate the relation map icon to the one of GraphQL?

![image](https://github.com/user-attachments/assets/2621df26-0b72-4180-88b3-be4df6057842)

2024-09-09 06:29 UTC, SiriusXT commented on docs/frontend_api/entities_fnote.js.html
> +    "relationMap": "bx bxl-graphql",
Previously, I didn't know that GraphQL was the name of a query language for APIs; I thought it was just an ordinary name.
I feel that using the following icons for the relation map and note map might be better:
1: 
![图片](https://github.com/user-attachments/assets/25c5e3da-c009-4851-a91a-445473b9cb1a)
2.
![图片](https://github.com/user-attachments/assets/1b7d91d8-a3d5-444e-8b1c-effcc957032a)
3.
![图片](https://github.com/user-attachments/assets/48462c84-8e68-44e0-8c74-9542754e9dde)

2024-09-09 11:31 UTC, eliandoran commented on docs/frontend_api/entities_fnote.js.html
> +    "relationMap": "bx bxl-graphql",
(1) seems wonderful.

2024-09-09 14:43 UTC, JYC333 approved these changes

2024-09-09 17:30 UTC, eliandoran approved these changes

2024-09-09 17:30 UTC, merged