Feature addition: Updated MFA
TriliumNext/Notes pull request #401
Opened 2024-09-07 17:26 UTC by chesspro13

*This is continued work from PR 163. I was struggling to make the branch merge friendly, so I  started from "scratch" on a new branch.*

Features added

    TOTP (Time-based One-Time Password) with recovery codes
    OAuth/OpenID sign on

To test TOTP:
You will need some sort of authentication app/extension prior to testing.

    Go to "Options" -> "MFA"
    Check the "Enable TOTP" checkbox
    Click the "Generate TOTP Secret" button
    Copy the generated secret to your authentication app/extension
    Click the "Generate Recovery Codes" button
    Copy the recovery codes. Recovery codes can only be used once in place of TOTP and will say the date/time they were used in zulu time on subsequent visits to this page.
    Save the secret in .env under "TOTP_SECRET"
    Restart trilium.
    Logout or navigate to login page. You can now use the TOTP or recovery codes to login.

To test Oauth/OpenID
You will need to setup a authentication provider. I tested with Authentik, Google, and 0Auth. This requires a bit of extra setup. Linked [here](https://developers.google.com/identity/openid-connect/openid-connect) is how to test this with Google.

    Setup Google or another provider. The key bits of information needed are

    Issuer URL (googles example is https://accounts.google.com/.well-known/openid-configuration
    Client ID
    Secret
    The redirect URL's needed are http://localhost:8080/ and http://localhost:8080/callback

    Go to "Options" -> "MFA"
    Check the "Enable Oauth/OpenID" checkbox
    Click the "Login to Configured OAuth Service" button. It should redirect you to the authentication provider.
    When you are redirected back, click the "Save User" button. It should show a toast with the user you logged in as for your provider.
    You can now login and out with the service provider and should be able to login and logout without using your password.

2024-09-07 23:00 UTC, perfectra1n commented
This is super cool, thanks for doing this. 

Is it also possible to configure the `.env` variables via the local environment variables? I was poking around in the commits, and didn't see any documentation modified for this change, but I'm assuming that you're saving those changes for once someone else with a much bigger brain than myself reviews it! :)

I'll also review the additional routes for the OTP.

2024-09-07 23:28 UTC, chesspro13 commented
@perfectra1n the environment variables can be set with environment variables (ie export TOTP_ENABLED="true"), -e with docker, and in a .env file in the root directory. 

Honestly I forgot to update documentation. Whoops!

2024-09-09 18:47 UTC, chesspro13 commented
@perfectra1n 

Docs in progress [here](https://github.com/TriliumNext/Docs/pull/108).

2024-09-13 09:17 UTC, JYC333 requested changes
Thanks for your great work! I didn't finish testing the functionality, but the setup steps need some changes I believe.

Since you are adding a new table, and it doesn't add it automatically. I got an error here:

![image](https://github.com/user-attachments/assets/63f86972-d97a-45dc-b3db-59fdb389e62c)

I'm not sure whether I'm doing something wrong, if not, I think this PR also need to fix the database migration stuff.

I don't know exactly how the database version is handled in Trilium, but for syncing, the database version should be the same. So after we merge this PR, it won't compatible with the latest Trilium from Zadam. (Correct me if I'm wrong) It could be the first big step for TriliumNext, not sure how careful we should be hhh.

Some minor stuffs I find so far:

1. MFA in option doesn't in the "right" place if I already have a database (I mean not start from scratch).
![image](https://github.com/user-attachments/assets/ab8782b0-08c8-43ce-b461-83f455fad47d)
2. We have already upgrade bootstrap from v4 to v5, so some layouts are changed. Not sure whether you would like to fix it in this PR, it's ok to do it in a seperate PR I guess.

2024-09-13 16:36 UTC, chesspro13 commented
@JYC333 I'll take any feedback I can get!

> Since you are adding a new table, and it doesn't add it automatically. I got an error here:

I do have a way to create the table if it doesn't exist, however it looks like it's in the wrong place since you got that error. I'll add it to the startup sequence. 

> I don't know exactly how the database version is handled in Trilium, but for syncing, the database version should be the same. So after we merge this PR, it won't compatible with the latest Trilium from Zadam. (Correct me if I'm wrong) It could be the first big step for TriliumNext, not sure how careful we should be hhh.

Do you mean the versioning change from BetterSqlite3? That was changed earlier with the dependency cleanup.

>     1. MFA in option doesn't in the "right" place if I already have a database (I mean not start from scratch).
>     2. We have already upgrade bootstrap from v4 to v5, so some layouts are changed. Not sure whether you would like to fix it in this PR, it's ok to do it in a seperate PR I guess.

I will look into it, but honestly my UI/UX skills are nothing to write home about.

2024-09-13 17:10 UTC, JYC333 commented
> Do you mean the versioning change from BetterSqlite3? That was changed earlier with the dependency cleanup.

No, I mean the database version for the syncing, I think the database version should be the same bewteen client and server. So the previous Trilium (like 0.63.7) won't be compatible. But I see sync version here also, so I'm not sure whether I'm right.

![image](https://github.com/user-attachments/assets/96560b69-7514-42e2-81a7-fcbbf7727dd9)

> I will look into it, but honestly my UI/UX skills are nothing to write home about.

You can also leave this for later if you don't want spend too much time on this, I can help with this.

2024-09-13 18:25 UTC, perfectra1n commented
I'm also not sure if it's just me, but running the branch on a brand new instance brings the following errors when navigating to the `setup` page:
```
{"message":"/usr/src/app/src/views/setup.ejs:6\n    4|     <meta charset=\"utf-8\">\n    5|     <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\n >> 6|     <title><%= t(\"setup.title\") %></title>\n    7| \n    8|     <style>\n    9|         .lds-ring {\n\nt is not defined"}
```

Full output of the Docker run command:
```bash
[root on DESKTOP-M0FBO5A] ~
 »  docker run -v /root/triliumtest:/home/node/trilium-data -p 8080:8080 gitea.example.com/perf3ct/testnotes:mfatest
No USER_UID specified, leaving 1000
No USER_GID specified, leaving 1000
(node:9) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Generated session secret
DB not initialized, please visit setup page - http://[your-server-host]:8080 to see instructions on how to initialize Trilium.
DB size: 4 KB
(node:9) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
{
  "appVersion": "0.90.6-beta",
  "dbVersion": 228,
  "nodeVersion": "v22.8.0",
  "syncVersion": 32,
  "buildDate": "2024-09-07T18:36:34Z",
  "buildRevision": "7c0d6930fa8f20d269dcfbcbc8f636a25f6bb9a7",
  "dataDirectory": "/home/node/trilium-data",
  "clipperProtocolVersion": "1.0",
  "utcDateTime": "2024-09-13T18:23:05.503Z"
}
CPU model: AMD Ryzen 7 5800X 8-Core Processor, logical cores: 16, freq: 0 Mhz
Trusted reverse proxy: false
App HTTP server starting up at port 8080
Listening on port 8080
200 GET /api/health-check with 15 bytes took 3ms
ReferenceError: /usr/src/app/src/views/setup.ejs:6
    4|     <meta charset="utf-8">
    5|     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
 >> 6|     <title><%= t("setup.title") %></title>
    7|
    8|     <style>
    9|         .lds-ring {

t is not defined
    at eval ("/usr/src/app/src/views/setup.ejs":12:7)
    at setup (/usr/src/app/node_modules/ejs/lib/ejs.js:703:17)
    at tryHandleCache (/usr/src/app/node_modules/ejs/lib/ejs.js:274:36)
    at exports.renderFile [as engine] (/usr/src/app/node_modules/ejs/lib/ejs.js:491:10)
    at View.render (/usr/src/app/node_modules/express/lib/view.js:135:8)
    at tryRender (/usr/src/app/node_modules/express/lib/application.js:657:10)
    at Function.render (/usr/src/app/node_modules/express/lib/application.js:609:3)
    at ServerResponse.render (/usr/src/app/node_modules/express/lib/response.js:1048:7)
    at setupPage (file:///usr/src/app/src/routes/setup.js:24:9)
    at Function.cb (file:///usr/src/app/src/routes/routes.js:377:34) {
  path: '/usr/src/app/src/views/setup.ejs'
}
200 GET /api/health-check with 15 bytes took 0ms
200 GET /api/health-check with 15 bytes took 1ms
```

I checked out the `feature/MFA` branch and then built the Docker container on it 👀

2024-09-13 18:25 UTC, perfectra1n commented
Oh, looks like it might be a fatfinger somewhere with the `t` in `setup.ejs` lol

2024-09-14 17:25 UTC, perfectra1n commented
Yeah I'm not sure why it can't find what `t` is supposed to be, [here](https://github.com/TriliumNext/Notes/blob/120f1677e8a102fb4713bf3ead779f242c296ad9/src/views/setup.ejs#L6), does it work for you when you create the Docker container @chesspro13 ?

2024-09-14 17:32 UTC, chesspro13 commented
> Since you are adding a new table, and it doesn't add it automatically. I got an error here:

@JYC333 I was able to reproduce this and fix it. 

 >No, I mean the database version for the syncing, I think the database version should be the same bewteen client and server. So the previous Trilium (like 0.63.7) won't be compatible. But I see sync version here also, so I'm not sure whether I'm right.

I'll have to look into that. I'm not familiar with the client version.

@perfectra1n When I build docker it is successful, however the setup page doesn't render any text when I tried it again.
![Screenshot from 2024-09-14 10-31-18](https://github.com/user-attachments/assets/f4f3bfed-982a-4144-a5e6-173b1f7af3e1)

Both `mobile.ejs` and `set_passowrd.ejs` have some too, but there are none in `login.ejs`. The only one I made modifications to is `login.ejs`.

2024-09-14 17:47 UTC, chesspro13 commented
@perfectra1n it looks like it is part of the `i18next` package for translations.

2024-09-14 18:19 UTC, perfectra1n commented
Hmm, I wonder why it's throwing an error then, @eliandoran do you have any idea why by chance?

2024-09-14 18:25 UTC, chesspro13 commented
@perfectra1n I can confirm that `i18next` is what is causing the text to not render. I'm unable to replicate your error. Have you updated all packages with `npm i`?

2024-09-14 18:27 UTC, perfectra1n commented
![image](https://github.com/user-attachments/assets/e4868686-388e-474b-81e8-98865b6dba1f)

I can confirm that I did not

2024-09-14 18:51 UTC, chesspro13 commented
> so you can't replicate the issue when using the Docker container?

@JYC333 I can't replicate your issue. When I build the docker image it runs, but when I navigate to `localhost:8080/setup` no text is rendered (the picture I posted above). I think we are both having issues with the same package, but I'm still confused why we are getting different results since we are using docker. I may be wildly wrong, but I'm guessing `i18next` needs to be installed prior to running the docker build script because the typescript gets compiled in `build-docker.sh` and copied to the container afterwards in the `Dockerfile`. My guess is it throws off the translations.  ¯\_(ツ)_/¯

2024-09-15 07:41 UTC, JYC333 commented
> > so you can't replicate the issue when using the Docker container?
> 
> @JYC333 I can't replicate your issue. When I build the docker image it runs, but when I navigate to `localhost:8080/setup` no text is rendered (the picture I posted above). I think we are both having issues with the same package, but I'm still confused why we are getting different results since we are using docker. I may be wildly wrong, but I'm guessing `i18next` needs to be installed prior to running the docker build script because the typescript gets compiled in `build-docker.sh` and copied to the container afterwards in the `Dockerfile`. My guess is it throws off the translations. ¯\_(ツ)_/¯

Sorry I didn't follow here, is the issue here you for the database issue?

And I didn't try to start with docker, I always run with `npm run start-server` for development, not sure what's the behaviors when using docker.

2024-09-15 08:02 UTC, eliandoran commented
> @perfectra1n I can confirm that `i18next` is what is causing the text to not render. I'm unable to replicate your error. Have you updated all packages with `npm i` after switching to the new branch?

There are still some bugs related to internationalization of the server that I'm trying to fix. If it occurs on 'develop' as well it can be ignored for this particular PR.

2024-09-27 05:01 UTC, perfectra1n commented
@chesspro13 is this still good for testing? :) 

I wonder what commits I would have to cherry pick to get the Docker container to build, or how would be best to test it...what have you been doing thus far to test it on your branch?

2024-09-29 23:32 UTC, chesspro13 commented
> > so you can't replicate the issue when using the Docker container?
> 
> @JYC333 I can't replicate your issue. When I build the docker image it runs, but when I navigate to `localhost:8080/setup` no text is rendered (the picture I posted above). I think we are both having issues with the same package, but I'm still confused why we are getting different results since we are using docker. I may be wildly wrong, but I'm guessing `i18next` needs to be installed prior to running the docker build script because the typescript gets compiled in `build-docker.sh` and copied to the container afterwards in the `Dockerfile`. My guess is it throws off the translations. ¯\_(ツ)_/¯

@perfectra1n I tried it in my dev environment as well as on a fresh VM today. The only issue I have is the one with i18next and text not showing up in the setup screen.

@JYC333 I got the conversations mixed up. That last message I tagged you in was probably supposed to tag @perfectra1n.

2024-10-30 13:09 UTC, minecraftchest1 commented on src/services/open_id.ts
> +    issuerBaseURL: "https://accounts.google.com/.well-known/openid-configuration",
Make this load `process.env.OPENID_CONFIG_URL', and now you have support for more services for OpenID Connect.

2024-11-04 18:33 UTC, JeffrinCh commented on package.json
> +    "dotenv": "^16.4.5",
Do we need dotenv now? we can use the inbuilt functionality of nodejs now https://nodejs.org/en/learn/command-line/how-to-read-environment-variables-from-nodejs

2024-12-10 21:39 UTC, eliandoran commented
Hi, @chesspro13 .

What's the status of this PR, do you have the time to work on it?

2024-12-17 17:31 UTC, pano9000 commented
quick comment on the env naming:

I personally feel like the env vars should be prefixed with some sort of code, to make sure they are clearly belonging to TriliumNext - which will reduce the chance of accidentally resetting/overwriting these.

E.g. instead of `TOTP_ENABLED` maybe it could be `TRILIUMNEXT_TOTP_ENABLED` or just `TRILIUM_TOTP_ENABLED`

What do you think?

2025-01-13 20:07 UTC, pano9000 commented
quick other remark: since this project seems to use ini files for setting some config options, I would think it makes sense to continue using the existing solution here as well, instead of going to the .env file way.

(Admittedly: yes, it also uses optional env variables, but these are e.g. used to "point" to the data-dir (via TRILIUM_DATA_DIR), where the ini file lies (or gets created, if not existing))

https://github.com/TriliumNext/Notes/blob/develop/config-sample.ini

what do you think?

2025-02-02 04:03 UTC, chesspro13 commented
@eliandoran I think I'm fairly close to closing up my personal project that pulled me away from working on Trilium, so I should be back here sometime this month. 

@pano9000 I'll look into implementing it that way. I didn't particularly like using .env, so that seems like a good solution.

2025-03-25 02:45 UTC, HyperCriSiS commented
Will this only be tied to google regarding SSO?
I would like to add SSO support for the Home Assistant Addon.

2025-03-25 09:25 UTC, JYC333 commented
This PR will not add more feature, other SSO supports can be added later. You can create a issue after this PR is merged to track this.

2025-03-26 10:06 UTC, JYC333 approved these changes

2025-03-26 20:44 UTC, eliandoran commented
@JYC333 , great job.

I've just started testing it and I can see a few relatively big problems with the UI/UX.

To setup TOTP on the server, I need to modify `config.ini`, otherwise all the options are disabled. If I enable the TOTP in the config, I'm asked to log using the password and the... TOTP that I did not configure.

This makes for a great chicken or the egg problem. I suppose it's because it was mostly meant for the desktop client and not the server?

I don't see why we shouldn't allow the user to generate TOTP even if it's not enabled. Or even better, not sure why we need to modify the `config.ini` and not activate it from the UI itself.

2025-03-26 21:35 UTC, JYC333 commented
> To setup TOTP on the server, I need to modify config.ini, otherwise all the options are disabled. If I enable the TOTP in the config, I'm asked to log using the password and the... TOTP that I did not configure.

The setting stuff I just follow what the PR have, but I have thought to allow user to change the setting in the app. I can make a change for that.

As for the login issue, I think after moving to allow user to change the setting in the app, that issue should be gone. I'll fix that.

> This makes for a great chicken or the egg problem. I suppose it's because it was mostly meant for the desktop client and not the server?

And I think this MFA is mostly for the server not for the desktop client, since we doesn't request login when you use desktop client. And it also doesn't request authentication when you want to sync with server if I remember correctly. That could be an issue that we need to fix later.

2025-03-28 02:50 UTC, JYC333 commented
TOTP is moved out from config.ini, and OAuth is still there for security concern. I think now it makes more sense now.

2025-03-28 20:11 UTC, maphew commented
so happy to see this happening, thank you. Is hardware auth like Yubikey or fingerprint reader part of this or would that be an additional feature?

2025-03-28 21:05 UTC, JYC333 commented
> so happy to see this happening, thank you. Is hardware auth like Yubikey or fingerprint reader part of this or would that be an additional feature?

I think that will be an additional feature then, at least won't in this PR.

2025-03-28 23:01 UTC, eliandoran requested changes
Almost there, @JYC333 ! :)

2025-03-29 02:28 UTC, perfectra1n commented
For TOTP_ENABLED and TOTP_SECRET - I believe that these variable names should be prepended with TRILIUM_ with our release of environment variables since this PR was created.

2025-03-29 10:25 UTC, JYC333 commented
> For TOTP_ENABLED and TOTP_SECRET - I believe that these variable names should be prepended with TRILIUM_ with our release of environment variables since this PR was created.

TOTP_ENABLED and TOTP_SECRET are removed from settings, and let user to config through option page. The settings that required for OAuth need to set through `config.ini`. I also add instructions for user if they want to set through environment variables.

2025-03-29 11:05 UTC, eliandoran approved these changes

2025-03-29 11:06 UTC, merged