Patch fr translation
TriliumNext/Notes pull request #530
Opened 2024-10-28 15:04 UTC by Potjoe-97

2024-10-31 21:00 UTC, eliandoran requested changes

2024-10-31 21:00 UTC, eliandoran commented on src/public/translations/fr/translation.json
> +    "onlyInDesktop": "Only in desktop (Electron build)",
@Potjoe-97 , shouldn't this be in French? I see the English translation was carried over instead.

2024-10-31 21:00 UTC, eliandoran commented on src/public/translations/fr/translation.json
> +    "failed": "Import failed: {{message}}."
Same here, not translated.

2024-10-31 21:00 UTC, eliandoran commented on src/public/translations/fr/translation.json
> +    "convert_into_attachment_prompt": "Are you sure you want to convert note '{{title}}' into an attachment of the parent note?"
Need translation.

2024-10-31 21:00 UTC, eliandoran commented on src/public/translations/fr/translation.json
> +    "note_source": "Code source",
Need translation.

2024-10-31 21:00 UTC, eliandoran commented on src/public/translations/fr/translation.json
> +    "custom_url_placeholder": "Customize search engine url",
Need translation.

2024-10-31 21:00 UTC, eliandoran commented on src/public/translations/fr/translation.json
> +    "unhoist-note": "Unhoist note",
Need translation.

2024-11-02 19:19 UTC, hasecilu commented
I don't know if you used the [translation](https://github.com/TriliumNext/Notes/blob/develop/bin/translation.sh) script but when using it, more specifically the `--update2` flag you need to make sure all strings are translated because otherwise PO editors could use the English string is there is no translation and there is no checks to avoid repeating source strings.

2024-11-03 09:39 UTC, Potjoe-97 commented
Sorry for the draft state of the PR. I use Crowdin to help me in the translation, and I updated the original source files before exporting my fixes for the last translation, resulting in numerous untranslated strings. Moreover, I'm a bit new to git, and I do have some difficulties managing branches / pr... Still learning :) @eliandoran I'm updating the files rn, all strings should be translated.

2024-11-05 00:38 UTC, eliandoran approved these changes
Thank you for your work!

2024-11-05 00:38 UTC, merged